### ISSUE TITLE
Incorrect typescript StringMap quoting

### ISSUE THREAD

**Issue by bacek** [timbod7/adl#108]
Typescript codegen doesn't quote keys in literal `StringMap`.

Consider this adl:

```
module test {

struct Test {
  StringMap<String> foo = {
    "$": "bar",
    " ": "baz"
  };
};

};

```

Generated code will have unquoted keys for `$` and ` ` (empty string).

```
export function makeTest(
  input: {
    foo?: {[key: string]: string},
  }
): Test {
  return {
    foo: input.foo === undefined ? {  : "baz", $ : "bar"} : input.foo,
  };
}
```

Correct version should be `foo: input.foo === undefined ? { " " : "baz", "$" : "bar"} : input.foo,`

**Comment by timbod7** [comment]
Fixed with b5f29ebaad6bd83ef0d996bc5169ce15f5ac8794
