### ISSUE TITLE
Rename Void primitive to Unit

### ISSUE THREAD

**Issue by timbod7** [timbod7/adl#113]
See the various names for the unit type here:

https://en.wikipedia.org/wiki/Unit_type

On popularity, the winner is `()` but this doesn't fit with ADLs syntax. Second place seems to go to `Unit`.

**Comment by paul-thompson-helix** [comment]
I believe it would be better to leave the ADL Void as-is.

Firstly for compatibility (mainly developer's mental compatibility) with ADL v0.
ie developers are accustomed to ADL Void and it's semantics.


Secondly I regard the semantics of unit types as follows:
"*a* unit type is a type that allows only one value ... it is customary to talk about *the* unit type and ignore the details of its value" https://en.wikipedia.org/wiki/Unit_type (emphasis mine)

The custom to "talk about *the* unit type" is (IMO) a natural choice when it comes to unit types internal to programming languages.
However in regards to externally serialised data there are different forms of unit type that have different serialised representations.
In particular for an ADL union, a field of (unit) type Void is represented differently than a field of type an empty struct (also a unit type).

In ADL Void is a particular unit type that has it's current behaviour of making unions serialise as their case label, as a struct field serialise as json null and some other cases (eg a Void annotation) the void value is able to be omitted entirely.

Reason why I don't think Void should be renamed as Unit:

"Unit" as a name is too broad as it could be confused with any type that is singly-valued.
There are already multiple unit types: Void and all empty structs.
Renaming Void to Unit might imply that any singlely-valued (ie unit) type will be detected and made to behave as Void currently does - which I assume is not the case and would not be desirable.

Therefore I believe ADL should retain the current definition and semantics of Void.

**Comment by timbod7** [comment]
Thanks for the considered comment.

> Firstly for compatibility (mainly developer's mental compatibility) with ADL v0.
ie developers are accustomed to ADL Void and it's semantics.

Agreed. This is for me the strongest reason to keep the status quo.

> "Unit" as a name is too broad as it could be confused with any type that is singly-valued.
There are already multiple unit types: Void and all empty structs.

I don't find this convincing. Other languages (such as rust and haskell) also have multiple unary types that are isomorphic, and call one of them "the unit type".

However, despite this, I'm tending towards saying "lets just keep the status quo".

**Comment by timbod7** [comment]
I'm convinced. Void stays!
