### ISSUE TITLE
Clean up adl output

### ISSUE THREAD

**Issue by anuraags** [timbod7/adl#29]
It would be useful to some intelligent truncation to the adl output or add colorisation so the messages are easier to sift through.

**Comment by timbod7** [comment]
Do you mean the error messages?

**Comment by anuraags** [comment]
Well, mainly I want to be able to differentiate the error messages against messages like:

`Reading /Users/asridhar/Development/Projects/adl/haskell/.stack-work/install/x86_64-osx/lts-5.18/7.10.3/share/x86_64-osx-ghc-7.10.3/adl-compiler-0.1.0.0/lib/adl/sys/annotations.adl...`

and

`leaving /Users/asridhar/Development/Projects/helix/jcms/flip/src/au/com/helixta/core/graphgenerator/doctor/adl/doctor/Hypertension.java unchanged.`

**Comment by timbod7** [comment]
How about I just add a verbose flag for messages like the above?

**Comment by anuraags** [comment]
Yep that works as well.

**Comment by timbod7** [comment]
Resolved with 16d412cd492314f720d6ed8c9e82c1e0cd03fbde
