### ISSUE TITLE
More meaningful exceptions in java deserialisation

### ISSUE THREAD

**Issue by anuraags** [timbod7/adl#32]
As an example, currently if you define an enum with a wrong value the deserialiser just throws an "IllegalStateException". It would be useful to have some more verbose error message here (i.e. which enum resulted in the error and what the value was).

**Comment by timbod7** [comment]
The error messages have been fixed with:

https://github.com/timbod7/adl/commit/44a37a7094310482e883f2ff367fdf217c62b13a
