### ISSUE TITLE
sys.types.Map initialiser should support "normal" JSON object literal (if primitive keys)

### ISSUE THREAD

**Issue by latos** [timbod7/adl#37]
i.e.

Map<String, String> foo = { "key1":"val1",  "key2":"val2" };

instead of

Map<String, String> foo = [ {"v1":"key1", "v2":"val1"},  {"v1":"key2", "v2":"val2"} ];
v1/v2 rather noisy and implementation detail leaky

**Comment by timbod7** [comment]
The primitive type `StringMap<>` has the serialization you expect. Use this if your keys are Strings.

I agree that the serialization of `Map<>` is noisy, but I don't think it's "leaking" implementation details. The mapping of ADL types to json is formalized and public. The ADL definition of map:

```
struct Pair<T1,T2>
{
    T1 v1;
    T2 v2;
};

newtype Map<K,V> = Vector<Pair<K,V>>;
```
directly implies the above serialization. Perhaps this isomorphic definition would be slightly preferable:

```
struct MapValue<K,V>
{
    K k;
    V v;
};

newtype Map<K,V> = Vector<MapValue<K,V>>;
```
