### ISSUE TITLE
Support optional struct fields (as opposed to nullable)

### ISSUE THREAD

**Issue by latos** [timbod7/adl#38]
Optional means the field can be absent (not null).

**Comment by timbod7** [comment]
Would a hypothetical:

```
struct X
{
    optional T value;
};
```

be equivalent to

```
struct X
{
    Nullable<T> value = null;
}
```

along with a change to the serialiser that left out fields which have default values?

**Comment by timbod7** [comment]
See https://tim.dockerz.net/posts/2020-04-17-optionality-in-adl.html for details
