### ISSUE TITLE
Fluid-style builders

### ISSUE THREAD

**Issue by latos** [timbod7/adl#39]
setters that return `this`

**Comment by timbod7** [comment]
The goal has been to generate java that matches standard conventions. A discussion on fluid style setters is here:

http://stackoverflow.com/questions/1345001/is-it-bad-practice-to-make-a-setter-return-this

The main drawback seems to be that some tooling expects void returning setters. But I can see the convenience. A compromise would be to have a flag to control this feature of the generated code.

**Comment by timbod7** [comment]
Explicit builder have been implemented in a20157e4ac20c721d5c212785412d2112611f4a2
