### ISSUE TITLE
`Void` type annotations without specifying `null` serialized value

### ISSUE THREAD

**Issue by rayningw** [timbod7/adl#45]
Currently, annotations of the `Void` type needs to specify `null` as the serialized value, e.g.

```
newtype Localizable = Void;

struct MyStruct {
    @Localizable null
    String name;
}
```

Since there can only be one value for a `Void` type, it would be good to make this implicit and allow annotations like so:

```
@Localizable
String name;
```

**Comment by timbod7** [comment]
Fixed with 48895ad3197043cbad3ef58322d409efc1919a59
