### ISSUE TITLE
Eliminate warnings from generated Java code

### ISSUE THREAD

**Issue by latos** [timbod7/adl#51]
E.g.

- @Override where appropriate e.g. on FACTORY & JsonBinding implementations
- Remove redundant type arguments e.g. new ArrayList<TypeExpr>() -> new ArrayList<>()

**Comment by timbod7** [comment]
Resolved with: 87e5800035adabbaf520d742be07bc142c7f1c63 df785c1b39737819ee1e1b2257441223c14948fd 4aac3e1f7d18cf7a2cfe0e46ee8de0edbbb2a1c3
