### ISSUE TITLE
org.adl.runtime.JsonBinding only created if --json is specified

### ISSUE THREAD

**Issue by millergarym** [timbod7/adl#67]
The RT depends on org.adl.runtime.JsonBinding, but it is only created if --json is specified.

**Comment by timbod7** [comment]
Hmmm. That's not so good. In practice I've always built with `--json`. Will look at this, but is there are reason you don't want to turn on on this flag?

**Comment by millergarym** [comment]
Just teething issues on my side.

If there is no reason to run `adlc java` without the `--json` then why have it?
Else change it to --no-json :-).

**Comment by timbod7** [comment]
Resolved  with

https://github.com/timbod7/adl/commit/9241e5c600b6ccc0b2ef2eba6d3c8ae2988407b3
