### ISSUE TITLE
[Question] How does this compare to Typedefs.com?

### ISSUE THREAD

**Issue by sideeffffect** [timbod7/adl#76]
Sorry if this is a wrong channel for such questions, but I would be interested how would you compate ADL with Typedefs :smile: 

https://github.com/typedefs/typedefs/

**Comment by timbod7** [comment]
Interesting. "typedefs" is new to me.

In principle it looks quite close to ADL. I'll take a look at revert.

**Comment by timbod7** [comment]
It seems that ADL and typedefs are approximately equivalent in terms of the algebraic data types they can describe. ADL can't define anonymous types: every type lives in a global namespace.

I can't really comment on the objectives of the typedefs system, but right now ADL seems more focused on language interoperability between mainstream programming languages, with language bindings for haskell, java, C++, typescript, rust, sql, etc. Also the [primitive types][1] built into ADL reflect primitives typically present in conventional languages.

The ADL language itself is modeled in ADL, making it possible to write meta-processing code in any of the supported language backends. typedefs appears to have similar capabilities.

Some other key features of ADL that I'm unsure of equivalents in typedefs:

- [custom type mappings][2]
- [Annotations][3] as means of capturing metadata about types

[1]:https://github.com/timbod7/adl/blob/master/docs/language.md#primitive-types
[2]:https://github.com/timbod7/adl/blob/master/docs/backend-haskell.md#custom-types
[3]:https://github.com/timbod7/adl/blob/master/docs/language.md#annotations
