### ISSUE TITLE
Property 'find' does not exist on type 'Map<ScopedName, {}>'.

### ISSUE THREAD

**Issue by jmatsushita** [timbod7/adl#78]
I get the following typescript error when running tsc after compiling `adl` types to typescript. 
```
types/gen/runtime/json.ts:472:27 - error TS2339: Property 'find' does not exist on type 'Map<ScopedName, {}>'.

472   const ann = annotations.find(el => scopedNamesEqual(el.v1, annScopedName));
```

**Comment by jmatsushita** [comment]
Oops, just had to target ES6 with `tsc -t ES6`

**Comment by timbod7** [comment]
Glad you worked this out. I've just added a comment to the documentation:

https://github.com/timbod7/adl/commit/47d13382cb739f0125beb105ee2db036a60c7fcf
