### ISSUE TITLE
C++ codegen fail on Nullable<T> xxx = null;

### ISSUE THREAD

**Issue by paul-thompson-helix** [timbod7/adl#96]

**Comment by paul-thompson-helix** [comment]
Also Nullable<T> c++ codegen doesn't compile.

**Comment by timbod7** [comment]
What C++ type should ADL `Nullable<>` map to?

I propose `std::optional` though this requires c++17.

**Comment by paul-thompson-helix** [comment]
Yes std::optional, let's roll forward onto c++17

**Comment by timbod7** [comment]
Fixed with f42788ea4d2be23fe100dbbd9da5e8a6204a2df2
